### ISSUE TITLE
repo name

### ISSUE THREAD

**Issue by delta1** [Nubuck/Z1-GANG-STARTER#1]
I'm all for meme life but I do think the repo name should be more descriptive if we are serious about getting people to use/contribute

what about Z1-web-app-starter ?

**Comment by Nubuck** [comment]
Z1 is gang. The ambition is for this repo to scale up to include desktop and mobile applications in the future, plus experimental features until Z1 gang HQ page, repos and registry are launched. Tbh it's still too early to expect contributions without substantial ground made in documentation and tooling. 😅
Since a Z1 surface is the name for a collection of apps on different platforms delivering a solution, perhaps we rename it to z1-surface-starter as that's what this repo should evolve into.🤔

**Comment by delta1** [comment]
> Tbh it's still too early to expect contributions 

Not with that attitude! :P 

> z1-surface-starter 

I do prefer that name but nobody knows what surface means, isn't that a Microsoft tablet? 

Food for thought

**Comment by Nubuck** [comment]
Yeah MS has a surface range... It's been a thorn in the core/surface convention for a while. Better name for something that wraps a core? 🤔
